/* Dermly — Journey home + streaks/shields + quests + achievements + product photos */
const $=(s,el=document)=>el.querySelector(s);
const app=$('#app'), tabbar=$('#tabbar'), toastEl=$('#toast');
const store={load(){try{return JSON.parse(localStorage.getItem('dermly_full')||'{}')}catch{return{}}},save(s){localStorage.setItem('dermly_full',JSON.stringify(s))}};
let S=Object.assign({route:'welcome',hist:[],quizStep:0,quiz:{goals:['Clearer-looking skin'],skinType:'Combination',concerns:['Oiliness','Uneven tone'],sensitivity:'Non-sensitive',budget:'Mid ($15-25)',region:'US',current:['Cleanser','Moisturizer']},logs:{},mood:{},tab:'today',selected:'p3',rem:{am:true,pm:true,amTime:'7:30 AM',pmTime:'10:00 PM',days:['M','T','W','T2','F']},chat:[],profile:{name:'Alex',age:'25-34',loc:'US'},
 xp:0,xpLog:[],awarded:{},lessonsDone:[],learnedIng:[],introduced:[],photos:[],scans:[],weekly:{goal:10,done:0,claimedWeek:''},streak:{count:0,shields:1,longest:0,lastActive:'',savedMsg:''},achUnlocked:[],pendingLevelUp:null,pendingAch:null},store.load());
if(!Array.isArray(S.hist))S.hist=[];
function persist(){store.save(S)}
function toast(m){toastEl.textContent=m;toastEl.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>toastEl.classList.add('hidden'),2200)}
function todayKey(d=new Date()){return d.toISOString().slice(0,10)}
function weekKey(){const d=new Date();const one=new Date(d.getFullYear(),0,1);return d.getFullYear()+'-W'+Math.ceil((((d-one)/86400000)+one.getDay()+1)/7)}
function setRoute(r,opts={}){if(!opts.replace&&S.route!==r){S.hist.push(S.route);if(S.hist.length>30)S.hist.shift()}S.route=r;persist();render();app.scrollTop=0}
function scoreColor(s){return s>=85?'var(--green)':s>=70?'var(--amber)':'var(--red)'}
function icons(){ if(window.lucide) lucide.createIcons() }
/* Back nav: every push is reversible. Tab roots never show back. */
const TAB_ROOTS={today:'journey',journey:'journey',routine:'routine',products:'products',progress:'progress',assistant:'assistant',profile:'profile'};
function canGoBack(){return S.hist.length>0}
function topbar(title,sub=''){if(!canGoBack()&&!title)return '';if(!canGoBack())return title?`<div class="topbar"><b>${title}</b>${sub?`<div class="small">${sub}</div>`:''}</div>`:'';return `<div class="topbar"><button class="backbtn" onclick="back()" aria-label="Go back"><i data-lucide="chevron-left"></i></button><div style="flex:1"><b>${title||'Back'}</b>${sub?`<div class="small">${sub}</div>`:''}</div><button class="backbtn" onclick="go('journey')" aria-label="Home"><i data-lucide="house"></i></button></div>`}
window.back=function(){if(S.pendingLevelUp){S.pendingLevelUp=null;persist();render();return}if(S.pendingAch){S.pendingAch=null;persist();render();return}const prev=S.hist.pop();if(prev){S.route=prev;const tabs={today:'today',journey:'today',routine:'routine','routine-detail':'routine',products:'products','product-detail':'products',recommendations:'products',vendors:'products','scan-product':'products',progress:'progress',learn:'progress','lesson':'progress',level:'progress',achievements:'profile',assistant:'assistant',reminders:'today',tracker:'today',profile:'profile'};if(tabs[prev])S.tab=tabs[prev];persist();render();app.scrollTop=0}else{setRoute('journey')}};
window.go=function(r,opts={}){const tabs={today:'today',journey:'today',routine:'routine','routine-detail':'routine',products:'products','product-detail':'products',recommendations:'products',vendors:'products','scan-product':'products',progress:'progress',learn:'progress','lesson':'progress',level:'progress',achievements:'profile',assistant:'assistant',reminders:'today',tracker:'today',profile:'profile'};if(tabs[r])S.tab=tabs[r];
 // tab-root resets stack (standard mobile behavior)
 if(['journey','today','routine','products','progress','assistant','profile'].includes(r)&&TAB_ROOTS[tabs[r]||r]===r){S.hist=[]}
 setRoute(r,opts)};

/* Product photos — real images, not placeholders */
const IMG={
 cleanse:'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=500&q=60',
 spf:'https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=500&q=60',
 serum:'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=500&q=60',
 gel:'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=500&q=60',
 bha:'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&w=500&q=60',
 pm:'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=500&q=60'};

/* ---- XP + levels ---- */
const LEVELS=[{n:'Rookie',xp:0,icon:'sprout'},{n:'Beginner',xp:100,icon:'leaf'},{n:'Consistent',xp:250,icon:'repeat'},{n:'Skin Smart',xp:500,icon:'brain'},{n:'Routine Pro',xp:850,icon:'layers'},{n:'Skin Strategist',xp:1250,icon:'swords'},{n:'Dermly Expert',xp:1750,icon:'crown'}];
function levelFor(xp){let li=0;LEVELS.forEach((L,i)=>{if(xp>=L.xp)li=i});return {i:li,...LEVELS[li],next:LEVELS[li+1]||null}}
function xpOnce(key){const k=todayKey()+':'+key;if(S.awarded[k])return false;S.awarded[k]=1;return true}
function addXP(pts,label,icon='zap'){const before=levelFor(S.xp).i;S.xp+=pts;S.xpLog.unshift({pts,label,day:todayKey()});S.xpLog=S.xpLog.slice(0,24);checkAch();const after=levelFor(S.xp).i;persist();xpFloat(pts,label,icon);if(after>before){S.pendingLevelUp=after;persist()}return true}
function xpFloat(pts,label,icon){let el=document.createElement('div');el.className='xp-float';el.innerHTML=`<div class="xp-pill"><i data-lucide="${icon}"></i> +${pts} XP · ${label}</div>`;$('#phone').appendChild(el);icons();setTimeout(()=>{el.remove();render()},1400)}

/* ---- Streaks with shield (Numo pause/Duolingo freeze/Alma saves) ---- */
function solidDay(d){const L=S.logs[d]||{};return Object.values(L).filter(v=>v==='done').length>=3}
function calcStreak(){const days=[];for(let i=0;i<30;i++){const d=new Date();d.setDate(d.getDate()-i);days.push(todayKey(d))}
 let count=0,gapUsed=false;const week=[];
 for(let i=0;i<7;i++){const d=days[i];const hit=solidDay(d);
  if(i===0&&!hit){week.unshift({d,hit:false,today:true});continue}
  if(hit){count++;week.unshift({d,hit:true})}
  else{if(count>0&&S.streak.shields>0&&!gapUsed){gapUsed=true;week.unshift({d,hit:false,saved:true})}else break}
 }
 // earn shield every 7 streak
 if(count>0&&count%7===0&&xpOnce('shield-'+count+'-'+days[0])){S.streak.shields=Math.min(3,S.streak.shields+1);toast('Shield earned')}
 S.streak.count=count;S.streak.longest=Math.max(S.streak.longest,count);
 S.streak.savedMsg=gapUsed?'Your streak shield protected your '+count+'-day streak.':'';persist();return {count,week,saved:gapUsed};
}
function checkAmPm(){const k=todayKey(),L=S.logs[k]||{};const am=ROUTINE.AM.every(s=>L[s.id]==='done'),pm=ROUTINE.PM.every(s=>L[s.id]==='done');
 if(am&&xpOnce('am-done'))addXP(20,'Morning routine complete','sun');
 if(pm&&xpOnce('pm-done'))addXP(20,'Evening routine complete','moon');
 if(am&&pm&&xpOnce('both-done'))addXP(10,'Full-day bonus · 50 total','flame');
 calcStreak();
 if(S.streak.count>=7&&xpOnce('streak7'))addXP(100,'7-day streak','flame');
 const wk=weekKey();let wDone=Object.keys(S.logs).filter(d=>Object.values(S.logs[d]).filter(v=>v==='done').length>=4).length;
 S.weekly.done=Math.min(wDone,S.weekly.goal);persist();
}
function xpHeader(){const L=levelFor(S.xp);const cur=L.xp,next=L.next?L.next.xp:L.xp+1;const pct=L.next?Math.min(100,Math.round((S.xp-cur)/(next-cur)*100)):100;
 return `<div class="xp-head" onclick="go('level')"><div class="xp-lvl"><div class="lvl-badge"><i data-lucide="${L.icon}"></i></div><div style="flex:1"><div style="font-size:11px;letter-spacing:.1em;opacity:.7">LEVEL 0${L.i+1} — ${L.n.toUpperCase()}</div><div style="font-weight:800;font-size:16px">${S.xp} XP ${L.next?`<span style="opacity:.6;font-weight:600;font-size:12px">· ${next-S.xp} to ${L.next.n}</span>`:'· Max'}</div></div><i data-lucide="chevron-right"></i></div><div class="xp-bar"><i style="width:${pct}%"></i></div></div>`}

/* ---- Achievements (Strava trophy case + Duolingo silhouettes + Mindvalley gems) ---- */
const ACH=[
 {id:'first',n:'First Cleanse',d:'Complete first routine step',icon:'droplets',test:()=>Object.keys(S.logs).length>0},
 {id:'builder',n:'Routine Builder',d:'Full AM + PM in one day',icon:'layers',test:()=>!!S.awarded[todayKey()+':both-done']||Object.values(S.awarded).some((v,k)=>String(k).includes('both-done'))},
 {id:'seven',n:'Seven Strong',d:'7-day streak',icon:'flame',test:()=>S.streak.longest>=7||S.streak.count>=7},
 {id:'detective',n:'Product Detective',d:'Scan 5 products',icon:'scan-search',test:()=>new Set(S.scans).size>=5||S.scans.length>=5},
 {id:'nerd',n:'Ingredient Nerd',d:'Learn 10 ingredients',icon:'flask-conical',test:()=>S.learnedIng.length>=10},
 {id:'spf',n:'SPF Soldier',d:'14 AM routines',icon:'sun',test:()=>Object.values(S.awarded).filter((v,k)=>String(k).includes('am-done')).length>=14||(S.xp>=300&&Object.keys(S.logs).length>=6)},
 {id:'smart',n:'Skin Smart',d:'Complete all lessons',icon:'brain',test:()=>S.lessonsDone.length>=4},
 {id:'master',n:'Routine Master',d:'30-day consistency',icon:'crown',test:()=>S.streak.longest>=30},
];
function checkAch(){ACH.forEach(a=>{if(!S.achUnlocked.includes(a.id)&&a.test()){S.achUnlocked.push(a.id);S.pendingAch=a.id;persist()}})}

const PRODUCTS=[
 {id:'p1',brand:'CeraVe',name:'Foaming Facial Cleanser',cat:'Cleanse',icon:'droplets',img:IMG.cleanse,price:'$13.93',fit:94,tier:'budget',when:'AM + PM daily',freq:'Daily',amount:'Pea-size, 30s',ingredients:[['Ceramides','Barrier support'],['Niacinamide','Oil + tone'],['Hyaluronic Acid','Hydration']],why:['Fits combination skin','Supports oil balance'],watch:'None major.',vendors:[{n:'Amazon',p:'$13.93',r:'4.8 Verified',ship:'2-day'},{n:'CVS',p:'$16.49',r:'4.6 Verified',ship:'Pickup'}]},
 {id:'p2',brand:'La Roche-Posay',name:'Anthelios SPF 50',cat:'Protect',icon:'sun',img:IMG.spf,price:'$22.99',fit:91,tier:'premium',when:'AM last step',freq:'Daily',amount:'2 finger-lengths',ingredients:[['Avobenzone','UV filters'],['Glycerin','Hydration']],why:['Daily SPF priority','Light for T-zone'],watch:'Reapply 2h in sun.',vendors:[{n:'Amazon',p:'$22.99',r:'4.9 Verified',ship:'2-day'},{n:'Ulta',p:'$24.99',r:'4.8 Verified',ship:'Pickup'}]},
 {id:'p3',brand:'The Ordinary',name:'Niacinamide 10% Serum',cat:'Treat',icon:'flask-conical',img:IMG.serum,price:'$9.80',fit:89,tier:'budget',when:'PM',freq:'2–3x/week',amount:'3-4 drops',ingredients:[['Niacinamide 10%','Tone + oil'],['Zinc 1%','Sebum appearance']],why:['Even tone','Starter active'],watch:'Separate from BHA.',vendors:[{n:'Sephora',p:'$9.80',r:'4.7 Verified',ship:'2-day'}]},
 {id:'p4',brand:'Neutrogena',name:'Hydro Boost Gel',cat:'Moisturize',icon:'droplet',img:IMG.gel,price:'$18.50',fit:87,tier:'mid',when:'AM + PM',freq:'Daily',amount:'Dime-size',ingredients:[['Hyaluronic Acid','Hydration'],['Glycerin','Humectant']],why:['Hydration priority'],watch:'None major.',vendors:[{n:'Target',p:'$18.50',r:'4.7 Verified',ship:'3-day'}]},
 {id:'p5',brand:'Paula’s Choice',name:'2% BHA Exfoliant',cat:'Treat',icon:'test-tube',img:IMG.bha,price:'$34.00',fit:68,tier:'premium',when:'PM only',freq:'1–2x/week max',amount:'Thin layer',ingredients:[['Salicylic Acid 2%','Texture']],why:['Helps texture'],watch:'Separate from niacinamide.',vendors:[{n:'Amazon',p:'$34.00',r:'4.8 Verified',ship:'2-day'}]},
 {id:'p6',brand:'CeraVe',name:'PM Moisturizer',cat:'Moisturize',icon:'moon',img:IMG.pm,price:'$16.20',fit:90,tier:'mid',when:'PM',freq:'Daily',amount:'Pea-size',ingredients:[['Ceramides','Barrier'],['Niacinamide','Tone']],why:['Evening hydration'],watch:'None major.',vendors:[{n:'CVS',p:'$16.20',r:'4.7 Verified',ship:'Pickup'}]},
];
const ROUTINE={
 AM:[{id:'am1',n:'01 Cleanse',t:'Gentle cleanser',icon:'droplets',img:IMG.cleanse,why:'Removes overnight oil.',how:'Pea-size, 30s.',when:'Every AM',freq:'Daily',p:'CeraVe Foaming'},{id:'am2',n:'02 Moisturize',t:'Light moisturizer',icon:'droplet',img:IMG.gel,why:'Locks hydration.',how:'Dime-size.',when:'Every AM',freq:'Daily',p:'Hydro Boost Gel'},{id:'am3',n:'03 Protect',t:'SPF 50',icon:'shield-check',img:IMG.spf,why:'Prevents dark-spot look.',how:'2 fingers, last.',when:'Every AM',freq:'Daily',p:'Anthelios SPF 50'}],
 PM:[{id:'pm1',n:'01 Cleanse',t:'Same cleanser',icon:'droplets',img:IMG.cleanse,why:'Clears day buildup.',how:'Same as AM.',when:'Every PM',freq:'Daily',p:'CeraVe Foaming'},{id:'pm2',n:'02 Treat',t:'Niacinamide serum',icon:'flask-conical',img:IMG.serum,why:'Even tone + oil.',how:'3-4 drops.',when:'PM only',freq:'2–3x/week',p:'Niacinamide 10%'},{id:'pm3',n:'03 Moisturize',t:'Night moisturizer',icon:'moon',img:IMG.pm,why:'Overnight barrier.',how:'Pea-size.',when:'Every PM',freq:'Daily',p:'CeraVe PM'}]
};
const LESSONS=[
 {id:'l1',t:'Layering order in 60 seconds',d:'Cleanse → Treat → Moisturize → SPF',icon:'layers',xp:25,body:'AM: Cleanse → Moisturize → SPF last. PM: Cleanse → Treat → Moisturize. Thin → thick.'},
 {id:'l2',t:'SPF without fear',d:'Amount + reapply',icon:'sun',xp:25,body:'2 finger-lengths AM last. Reapply 2h in sun.'},
 {id:'l3',t:'Niacinamide vs BHA',d:'Separate nights',icon:'flask-conical',xp:25,body:'Mon/Wed/Fri niacinamide, Thu BHA 1–2x/week.'},
 {id:'l4',t:'Introduce a product',d:'Patch test + 2 weeks',icon:'test-tube',xp:25,body:'1 at a time, 2–3x/week 2 weeks → daily if calm.'},
];
const SCREENS=[['journey','★ Journey'],['routine','7 Routine'],['products','9 Search'],['scan-product','11 Scan'],['learn','★ Lessons'],['level','★ Level'],['achievements','★ Badges'],['progress','16 Progress'],['assistant','17 Coach'],['profile','18 Profile']];

/* ---- Views ---- */
function vWelcome(){return `${xpHeader()}<div class="hero"><div class="lovi-orb"></div><h1>Hi, I'm Dermly!<br>Level up your consistency</h1><p class="muted">Skin isn't scored. Habits are.</p></div><button class="btn btn-primary" onclick="go('quiz')">Let's start!</button><button class="btn btn-ghost" onclick="go('journey')">See my Journey</button>`}
function vQuiz(){const steps=[
 {k:'goals',t:'What do you want?',sub:'Pick up to 3',opts:[['Clearer-looking skin','Fewer breakouts'],['Reduce excess oil','Less shine'],['Improve hydration','Less tight'],['Even-looking tone','Spots'],['Improve texture','Smoother'],['Maintain','Simple']]},
 {k:'skinType',t:'Skin type?',sub:'Best guess OK',opts:[['Dry','Flaky'],['Oily','Shiny'],['Combination','Oily T, dry cheeks'],['Balanced','Neither']]},
 {k:'concerns',t:'Main concerns?',sub:'Up to 3',opts:[['Oiliness','Pores'],['Dryness','Tight'],['Uneven tone','Blotchy'],['Dark spots','Marks'],['Texture','Bumpy'],['Redness','Flush']]},
 {k:'current',t:'What do you use?',sub:'Avoid duplicates',opts:[['Cleanser','Wash'],['Serum','Treat'],['Moisturizer','Cream'],['Sunscreen','SPF'],['Exfoliant','Acids'],['None','Fresh']]},
 {k:'budget',t:'Budget?',sub:'For picks',opts:[['Budget (<$15)','Drugstore'],['Mid ($15-25)','Core'],['Premium ($25+)','Derm'],['Mix','Value']]}];
 const i=Math.min(S.quizStep,steps.length-1),st=steps[i];const get=k=>k==='goals'?S.quiz.goals:k==='concerns'?S.quiz.concerns:k==='current'?S.quiz.current:[S.quiz[k]];
 return `<div class="small">${i+1} / ${steps.length}</div><div class="q-bubble"><span class="mini-orb">◠‿◠</span><span>${st.t}<br><span class="small">${st.sub}</span></span></div><div class="opt-list">${st.opts.map(([v,d])=>{const sel=get(st.k).includes(v);return `<div class="opt-row ${sel?'selected':''}" onclick="pick('${st.k}','${v}')"><div><b>${v}</b><div class="small">${d}</div></div><div class="radio">${sel?'<i data-lucide="check"></i>':''}</div></div>`}).join('')}</div><button class="btn btn-primary" onclick="quizNav(1)">${i===steps.length-1?'Continue':'Next'}</button>`}
window.pick=function(k,v){const m=['goals','concerns','current'];if(m.includes(k)){let a=S.quiz[k];a=a.includes(v)?a.filter(x=>x!==v):[...a,v].slice(0,3);if(!a.length)a=[v];S.quiz[k]=a}else S.quiz[k]=v;persist();render()};
window.quizNav=function(d){S.quizStep+=d;if(S.quizStep<0)S.quizStep=0;if(S.quizStep>4){S.quizStep=0;setRoute('scan-intro');return}persist();render()};
function vScanIntro(){return `<div class="hero"><div class="hero-ill"><i data-lucide="scan-face"></i></div><div class="q-bubble"><span class="mini-orb">◠‿◠</span><span>AI Face scanner.<br><span class="small">Estimate only.</span></span></div></div><button class="btn btn-primary" onclick="go('scan-cam')">Make a face scan</button><button class="btn btn-ghost" onclick="go('analysis')">Not now</button>`}
function vScanCam(){setTimeout(()=>{if(S.route==='scan-cam')setRoute('analysis')},2000);return `<div class="scan-frame"><div class="scan-visual"><div class="scan-line"></div><div class="face-oval"><i data-lucide="scan-face"></i></div></div><div style="padding:14px"><b>Capturing…</b></div></div>`}
function vAnalysis(){return `<h2>We see…</h2><div class="card"><div class="kv"><span>Oiliness</span><span>Moderate</span></div><div class="progress"><i style="width:65%"></i></div><div class="small">Estimate — never your score.</div></div><button class="btn btn-primary" onclick="go('snapshot')">See Profile</button>`}
function vSnapshot(){return `${xpHeader()}<h2>${S.quiz.skinType}</h2><div class="card"><div class="small">Goals: ${S.quiz.goals.join(', ')}</div></div><button class="btn btn-primary" onclick="go('journey')">Start my Journey</button>`}

/* JOURNEY HOME — replaces routine dump */
function vJourney(){const {count,week,saved}=calcStreak();const k=todayKey(),L=S.logs[k]||{};
 const amDone=ROUTINE.AM.every(s=>L[s.id]==='done'),pmDone=ROUTINE.PM.every(s=>L[s.id]==='done');
 const amCount=ROUTINE.AM.filter(s=>L[s.id]==='done').length,pmCount=ROUTINE.PM.filter(s=>L[s.id]==='done').length;
 const scansToday=new Set(S.scans.filter(s=>s.endsWith(k))).size;
 const daily=[{id:'am',n:'Morning routine',d:amCount+'/3 · Cleanse → Moisturize → SPF',xp:20,done:amDone,icon:'sun',go:'routine'},{id:'pm',n:'Evening routine',d:pmCount+'/3 · Cleanse → Treat → Moisturize',xp:20,done:pmDone,icon:'moon',go:'routine'},{id:'scan',n:'Scan a product',d:scansToday>0?'Done today':'Barcode or ingredients',xp:10,done:scansToday>0,icon:'barcode',go:'scan-product'},{id:'learn',n:'Complete a lesson',d:S.lessonsDone.length+'/4 mastered',xp:25,done:false,icon:'graduation-cap',go:'learn'}];
 const wk=weekKey();const wDone=S.weekly.done;
 return `${xpHeader()}
 <div class="journey-hero"><div style="display:flex;gap:12px;align-items:center"><div class="streak-flame"><i data-lucide="flame"></i></div><div style="flex:1"><div style="font-size:12px;opacity:.7">CURRENT STREAK</div><div style="font-size:26px;font-weight:800">${count} DAYS</div><div style="font-size:12px;opacity:.75">You're building a real habit.</div></div><div style="text-align:center"><i data-lucide="shield-check"></i><div style="font-weight:800">${S.streak.shields}</div><div style="font-size:10px;opacity:.7">shields</div></div></div>
 <div class="weekdots">${week.map(w=>`<div class="wdot ${w.hit?'hit':''} ${w.saved?'save':''}">${w.saved?'<i data-lucide="shield" style="width:14px;height:14px"></i>':(w.hit?'<i data-lucide="check" style="width:14px;height:14px"></i>':w.d.slice(5))}</div>`).join('')}</div>
 ${S.streak.savedMsg?`<div class="small" style="color:#9BE8B8;margin-top:8px"><i data-lucide="shield-check"></i> ${S.streak.savedMsg}</div>`:''}</div>
 <div class="shield-card"><div class="shield-ic"><i data-lucide="shield"></i></div><div style="flex:1"><b>Streak Shield × ${S.streak.shields}</b><div class="small">Earn 1 per 7-day streak (max 3). Miss a day = shield auto-protects, no stress.</div></div></div>
 <div class="ds-label"><i data-lucide="swords"></i> Your skin journey</div>
 <div class="ds-label">Daily quests</div>
 ${daily.map(q=>`<div class="quest ${q.done?'done':''}" onclick="go('${q.go}')"><div class="qic"><i data-lucide="${q.icon}"></i></div><div style="flex:1"><b>${q.n}</b><div class="small">${q.d}</div></div><span class="pill">+${q.xp}</span>${q.done?'<i data-lucide="check-circle-2"></i>':''}</div>`).join('')}
 <div class="ds-label">Weekly quest — Consistency Challenge</div>
 <div class="quest"><div class="qic"><i data-lucide="trophy"></i></div><div style="flex:1"><b>Complete routine 10× this week</b><div class="progress" style="margin-top:6px"><i style="width:${Math.min(100,wDone/S.weekly.goal*100)}%"></i></div><div class="small">${wDone} / ${S.weekly.goal}</div></div>${S.weekly.claimedWeek===wk?'<i data-lucide="check"></i>':'<span class="pill">+150</span>'}</div>
 ${S.weekly.done>=S.weekly.goal&&S.weekly.claimedWeek!==wk?'<button class="btn btn-primary" onclick="claimWeekly()">Claim +150 XP</button>':''}
 <div class="ds-label">Today's path</div><div class="path">
  <div class="path-node ${amDone?'done':'now'}"><span class="step-tag">AM Ritual</span><b> Morning routine</b><div class="small">${amCount}/3 · ${amDone?'Complete +20 earned':'Tap to complete'}</div><button class="mini primary" style="margin-top:8px" onclick="go('routine')">Open</button></div>
  <div class="path-node"><span class="step-tag">Knowledge</span><b> One lesson</b><div class="small">Layering, SPF, actives — Pokédex for face</div><button class="mini" style="margin-top:8px" onclick="go('learn')">Learn +25</button></div>
  <div class="path-node ${pmDone?'done':''}"><span class="step-tag">PM Ritual</span><b> Evening routine</b><div class="small">${pmCount}/3</div><button class="mini" style="margin-top:8px" onclick="go('routine')">Open</button></div>
 </div>
 <div class="ds-label">Picks with photos</div><div class="ptwo">${PRODUCTS.slice(0,4).map(p=>`<div class="pcard2" onclick="openProduct('${p.id}')"><img class="pimg" style="height:110px" src="${p.img}" alt="${p.name}" loading="lazy"><div class="pad"><b style="font-size:13px">${p.brand} ${p.name}</b><div class="small">${p.price} · <b style="color:${scoreColor(p.fit)}">${p.fit}</b></div></div></div>`).join('')}</div>
 <div class="ds-label">Achievements preview</div>${achPreview()}`}
function achPreview(){const un=ACH.filter(a=>S.achUnlocked.includes(a.id)).length;return `<div class="card" onclick="go('achievements')" style="cursor:pointer"><b><i data-lucide="medal"></i> ${un}/8 badges</b><div class="ach-grid" style="margin-top:10px">${ACH.slice(0,3).map(a=>{const u=S.achUnlocked.includes(a.id);return `<div class="ach ${u?'unlocked':'locked'}"><div class="ach-ic"><i data-lucide="${u?a.icon:'lock'}"></i></div><div class="small"><b>${a.n}</b></div></div>`}).join('')}</div><div class="small" style="margin-top:8px;color:var(--primary)">View all →</div></div>`}
window.claimWeekly=function(){S.weekly.claimedWeek=weekKey();addXP(150,'Weekly goal complete','trophy')};

/* Routine with photos */
function stepRow(s,tod){const k=todayKey(),st=(S.logs[k]||{})[s.id]||'todo';const p=PRODUCTS.find(x=>x.name.includes(s.p.split(' ')[0]))||PRODUCTS[2];return `<div class="card" style="padding:14px"><div style="display:flex;gap:8px;align-items:center;margin-bottom:10px"><span class="step-tag">${s.n}</span><span class="pill" style="margin-left:auto">${tod}</span></div><div style="display:flex;gap:12px"><img class="pthumb" src="${s.img||p.img}" alt="${s.p}" loading="lazy"><div style="flex:1"><b>${s.p}</b><div class="small">${s.how}</div><div style="display:flex;gap:6px;margin-top:6px"><span class="pill fit">${p.fit}% fit</span><span class="pill verified"><i data-lucide="badge-check"></i> Verified</span></div></div></div><div class="small" style="margin-top:8px"><b>Why:</b> ${s.why}</div><div style="display:flex;gap:8px;margin-top:8px"><span class="pricepill">${p.price}</span><span style="flex:1"></span><button class="mini ${st==='done'?'':'primary'}" onclick="event.stopPropagation();logStep('${s.id}','done')">${st==='done'?'Done':'Mark done'}</button></div></div>`}
window.logStep=function(id,v){const k=todayKey();S.logs[k]=S.logs[k]||{};S.logs[k][id]=v;persist();checkAmPm();render();toast(v==='done'?'Logged.':'Skipped.')};
window.openStep=function(id){S.stepId=id;setRoute('routine-detail')};
function vRoutine(){return `${xpHeader()}<h2 style="text-align:left">Routine for you</h2><div class="chips"><span class="chip active"><i data-lucide="sun"></i> Morning +20</span><span class="chip"><i data-lucide="moon"></i> Evening +20</span></div><div class="ds-label">Morning</div>${ROUTINE.AM.map(s=>stepRow(s,'AM')).join('')}<div class="ds-label">Evening</div>${ROUTINE.PM.map(s=>stepRow(s,'PM')).join('')}<button class="btn btn-primary" onclick="go('journey')">Back to Journey</button>`}
function vRoutineDetail(){const all=[...ROUTINE.AM.map(s=>({...s,tod:'AM'})),...ROUTINE.PM.map(s=>({...s,tod:'PM'}))];const s=all.find(x=>x.id===S.stepId)||all[1];return `<a href="#" onclick="go('routine');return false" class="small">← Routine</a><img class="pimg" src="${s.img}" alt=""><h2>${s.n}: ${s.t}</h2><div class="card"><b>What?</b><div class="small">${s.p}</div></div><div class="card"><b>Why?</b><div class="small">${s.why}</div></div><div class="card"><b>How?</b><div class="small">${s.how} · ${s.freq}</div></div><button class="btn btn-primary" onclick="logStep('${s.id}','done')">Mark done</button>`}
function vProducts(q=''){const list=PRODUCTS.filter(p=>(p.name+p.brand+p.cat).toLowerCase().includes((q||'').toLowerCase()));return `${xpHeader()}<h2 style="text-align:left"><i data-lucide="search"></i> Products</h2><div class="search-row"><input placeholder="Search…" value="${q||''}" oninput="rerenderProducts(this.value)"><button class="mini primary" onclick="go('scan-product')"><i data-lucide="barcode"></i></button></div><div class="ptwo" id="plist">${list.map(p=>`<div class="pcard2" onclick="openProduct('${p.id}')"><img class="pimg" src="${p.img}" alt="${p.name}" loading="lazy"><div class="pad"><div style="display:flex;gap:6px"><span class="pill fit">${p.fit}%</span></div><b style="font-size:13px">${p.brand} ${p.name}</b><div class="small">${p.cat} · ${p.price}</div></div></div>`).join('')}</div>`}
window.rerenderProducts=function(v){S.route='products';persist();const list=PRODUCTS.filter(p=>(p.name+p.brand+p.cat).toLowerCase().includes(v.toLowerCase()));$('#plist').innerHTML=list.map(p=>`<div class="pcard2" onclick="openProduct('${p.id}')"><img class="pimg" src="${p.img}" alt=""><div class="pad"><b style="font-size:13px">${p.brand} ${p.name}</b><div class="small">${p.fit}/100</div></div></div>`).join('');icons()};
window.openProduct=function(id){S.selected=id;setRoute('product-detail')};
window.learnIng=function(n){if(!S.learnedIng.includes(n+todayKey())){S.learnedIng.push(n+todayKey());addXP(10,'Learned '+n,'book-open')}else toast('Already logged')};
function vProductDetail(){const p=PRODUCTS.find(x=>x.id===S.selected)||PRODUCTS[2];return `<a href="#" onclick="go('products');return false" class="small">← Search</a><img class="pimg" src="${p.img}" alt="${p.name}"><h2 style="margin-top:10px">${p.brand} ${p.name}</h2><div class="small">${p.cat} · ${p.price} · ${p.when}</div><div class="card"><div class="match-wrap"><div class="ring" style="--score:${p.fit}"><span>${p.fit}</span></div><div><b>Dermly Match</b><div class="small">${p.when} · ${p.freq}</div></div></div><div style="display:flex;gap:8px;margin-top:10px"><span class="pill fit"><i data-lucide="check"></i> High skin fit</span><span class="pill">Average efficacy</span><span class="pill verified">Excellent safety</span></div></div><div class="card"><b><i data-lucide="flask-conical"></i> Tap ingredient +10</b>${p.ingredients.map(([n,d])=>`<div class="vendor" onclick="learnIng('${n}')" style="cursor:pointer"><span><b>${n}</b><div class="small">${d}</div></span><span class="pill">+10</span></div>`).join('')}</div><div class="btn-row"><button class="btn btn-ghost" onclick="go('vendors')">Vendors</button><button class="btn btn-primary" onclick="introduce('${p.id}')">Add +50</button></div>`}
window.introduce=function(id){if(!S.introduced.includes(id)){S.introduced.push(id);addXP(50,'New product introduced','package-plus')}else{toast('In routine');go('routine')}};
function vScanProduct(){return `${xpHeader()}<h2><i data-lucide="barcode"></i> Can I use this? +10</h2><div class="scan-frame"><div class="scan-visual"><div class="scan-line"></div><i data-lucide="barcode" style="width:60px;height:60px;color:#fff"></i></div><div style="padding:14px"><button class="btn btn-primary" onclick="mockScan()">Scan now</button></div></div><div id="scanRes"><div class="opt-list"><div class="opt-row" onclick="mockScan('p3')"><img class="pthumb" style="width:40px;height:48px" src="${IMG.serum}"><div><b>Niacinamide → 89</b></div></div><div class="opt-row" onclick="mockScan('p5')"><img class="pthumb" style="width:40px;height:48px" src="${IMG.bha}"><div><b>BHA → 68</b></div></div></div></div>`}
window.mockScan=function(id='p3'){const p=PRODUCTS.find(x=>x.id===id);S.scans.push(id+todayKey());if(xpOnce('scan-'+id))addXP(10,'Scanned '+p.name,'barcode');checkAch();persist();$('#scanRes').innerHTML=`<div class="card"><img class="pimg" style="height:120px" src="${p.img}"><b>${p.brand} ${p.name} · ${p.fit}</b><div class="btn-row" style="margin-top:8px"><button class="btn btn-ghost" onclick="openProduct('${p.id}')">Details</button><button class="btn btn-primary" onclick="go('vendors')">Buy</button></div></div>`;icons();};
function vRecs(){const card=p=>`<div class="pcard2" onclick="openProduct('${p.id}')"><img class="pimg" style="height:120px" src="${p.img}"><div class="pad"><b style="font-size:13px">${p.brand} ${p.name}</b><div class="small">${p.price} · ${p.fit}/100</div></div></div>`;return `${xpHeader()}<h2 style="text-align:left">Recommendations</h2><div class="ds-label">Best match</div>${card([...PRODUCTS].sort((a,b)=>b.fit-a.fit)[0])}<div class="ds-label">More</div><div class="ptwo">${PRODUCTS.slice(1,5).map(card).join('')}</div>`}
function vVendors(){const p=PRODUCTS.find(x=>x.id===S.selected)||PRODUCTS[2];return `<a href="#" onclick="go('product-detail');return false" class="small">←</a><h2><i data-lucide="store"></i> Vendors</h2><img class="pimg" style="height:120px" src="${p.img}">${p.vendors.map(v=>`<div class="card"><div class="setrow"><span><b>${v.n}</b><div class="small">${v.r} · ${v.ship}</div></span><b>${v.p}</b></div></div>`).join('')}`}
function vReminders(){const r=S.rem;return `<h2><i data-lucide="bell"></i> Reminders</h2><div class="card"><div class="setrow"><span><b>Morning ${r.amTime}</b></span><button class="toggle ${r.am?'on':''}" onclick="togRem('am')"></button></div><div class="setrow"><span><b>Evening ${r.pmTime}</b></span><button class="toggle ${r.pm?'on':''}" onclick="togRem('pm')"></button></div></div><button class="btn btn-primary" onclick="go('journey')">Save → Journey</button>`}
window.togRem=function(k){S.rem[k]=!S.rem[k];persist();render()};
function vProgress(){return `${xpHeader()}<h2 style="text-align:left">Progress</h2><div class="card"><b>Week 1 → 4 → 8</b><div class="timeline">${['W1','W4','W8'].map(a=>`<div class="tcard">${a}</div>`).join('')}</div><button class="mini primary" onclick="addPhoto()">Add photo +20</button></div><div class="card"><b>Lessons</b><button class="mini primary" onclick="go('learn')">Learn +25</button></div>`}
window.addPhoto=function(){if(xpOnce('photo')){S.photos.push(todayKey());addXP(20,'Progress photo','camera')}else toast('Already +XP today')};
function vLearn(){return `${xpHeader()}<h2 style="text-align:left">Lessons +25</h2>${LESSONS.map(l=>{const done=S.lessonsDone.includes(l.id);return `<div class="lesson ${done?'done':''}" onclick="goLesson('${l.id}')"><div class="lic"><i data-lucide="${l.icon}"></i></div><div style="flex:1"><b>${l.t}</b><div class="small">${l.d}</div></div>${done?'<i data-lucide="check-circle-2"></i>':'<span class="pill">+25</span>'}</div>`}).join('')}`}
window.goLesson=function(id){S.lessonId=id;setRoute('lesson')};
function vLesson(){const l=LESSONS.find(x=>x.id===S.lessonId)||LESSONS[0];const done=S.lessonsDone.includes(l.id);return `<a href="#" onclick="go('learn');return false" class="small">← Lessons</a><h2>${l.t}</h2><div class="card"><p class="muted" style="text-align:left">${l.body}</p></div>${done?'<div class="pill green">Mastered</div>':'<button class="btn btn-primary" onclick="completeLesson()">Complete +25 XP</button>'}`}
window.completeLesson=function(){if(!S.lessonsDone.includes(S.lessonId)){S.lessonsDone.push(S.lessonId);addXP(25,'Lesson complete','graduation-cap')}else go('learn')};
function vAssistant(){if(!S.chat.length)S.chat=[{who:'ai',t:'Coach here.'}];return `${xpHeader()}<h2>Coach</h2><div id="chat">${S.chat.map(m=>`<div class="bubble ${m.who}">${m.t}</div>`).join('')}</div><div class="chatbar"><input id="ask" placeholder="Ask…" onkeydown="if(event.key==='Enter')sendAsk()"><button class="mini primary" onclick="sendAsk()"><i data-lucide="send"></i></button></div>`}
window.sendAsk=function(){const el=$('#ask');const q=(el&&el.value||'').trim()||'Which goes first?';S.chat.push({who:'user',t:q});S.chat.push({who:'ai',t:'AM: Cleanse → Moisturize → SPF. PM: Cleanse → Treat → Moisturize.'});persist();render()};
function vLevel(){const L=levelFor(S.xp);return `<div class="xp-head"><div class="xp-lvl"><div class="lvl-badge"><i data-lucide="${L.icon}"></i></div><div><div style="font-size:11px;opacity:.7">LEVEL 0${L.i+1}</div><div style="font-weight:800;font-size:20px">${L.n} · ${S.xp} XP</div></div></div></div>${LEVELS.map((l,i)=>`<div class="quest ${S.xp>=l.xp?'done':''}"><div class="qic"><i data-lucide="${l.icon}"></i></div><div style="flex:1"><b>LEVEL 0${i+1} — ${l.n}</b><div class="small">${l.xp} XP</div></div></div>`).join('')}`}
function vAch(){return `${xpHeader()}<h2 style="text-align:left"><i data-lucide="medal"></i> Achievements ${S.achUnlocked.length}/8</h2><p class="small" style="text-align:left">From Mobbin patterns: Strava trophy case + Duolingo silhouettes. Unlocked on profile.</p><div class="ach-grid">${ACH.map(a=>{const u=S.achUnlocked.includes(a.id);return `<div class="ach ${u?'unlocked':'locked'}"><div class="ach-ic"><i data-lucide="${u?a.icon:'lock'}"></i></div><div class="small"><b>${a.n}</b><br>${a.d}</div></div>`}).join('')}</div>`}
function vProfile(){const L=levelFor(S.xp);return `${xpHeader()}<h2>Profile</h2><div class="card"><b>${S.profile.name} · ${L.n}</b><div class="small">${S.xp} XP · ${S.streak.count}-day streak · ${S.streak.shields} shields · ${S.achUnlocked.length}/8 badges</div><div class="btn-row" style="margin-top:10px"><button class="mini primary" onclick="go('achievements')"><i data-lucide="medal"></i> Badges</button><button class="mini" onclick="go('level')">Levels</button></div></div><div class="card"><b>Badges preview</b><div class="ach-grid" style="margin-top:8px">${ACH.slice(0,6).map(a=>{const u=S.achUnlocked.includes(a.id);return `<div class="ach ${u?'unlocked':'locked'}"><div class="ach-ic"><i data-lucide="${u?a.icon:'lock'}"></i></div><div class="small">${a.n}</div></div>`}).join('')}</div></div><div class="card"><b>Sitemap</b><div class="sitemap">${SCREENS.map(([r,l])=>`<button onclick="go('${r}')">${l}</button>`).join('')}</div></div><button class="btn btn-ghost" onclick="localStorage.removeItem('dermly_full');location.reload()">Reset</button>`}

function levelModal(){const i=S.pendingLevelUp;if(i==null)return '';const L=LEVELS[i];return `<div class="lvl-modal"><div class="lvl-card"><div class="lvl-ring"><span>${i+1}</span></div><div class="pill" style="margin:0 auto">LEVEL UP</div><h2>LEVEL 0${i+1}<br>${L.n}</h2><p class="muted">Better habits, not better skin.</p><button class="btn btn-primary" onclick="dismissLvl()">Continue</button></div></div>`}
window.dismissLvl=function(){S.pendingLevelUp=null;persist();render()};
function achModal(){if(!S.pendingAch)return '';const a=ACH.find(x=>x.id===S.pendingAch);if(!a)return '';return `<div class="lvl-modal"><div class="lvl-card"><div class="ach-ic" style="width:72px;height:72px;margin:0 auto 10px;background:var(--primary-grad);color:#fff;border-radius:50%;display:grid;place-items:center"><i data-lucide="${a.icon}" style="width:32px;height:32px"></i></div><div class="pill" style="margin:0 auto">ACHIEVEMENT</div><h2>${a.n}</h2><p class="muted">${a.d}</p><button class="btn btn-primary" onclick="dismissAch()">Collect</button></div></div>`}
window.dismissAch=function(){S.pendingAch=null;persist();render()};

function render(){const r=S.route;const showTabs=['today','journey','tracker','routine','routine-detail','products','product-detail','recommendations','vendors','scan-product','progress','learn','lesson','level','achievements','assistant','reminders','profile'].includes(r);tabbar.classList.toggle('hidden',!showTabs);let h='';
 if(r==='welcome')h=vWelcome();else if(r==='quiz')h=vQuiz();else if(r==='scan-intro')h=vScanIntro();else if(r==='scan-cam')h=vScanCam();else if(r==='analysis')h=vAnalysis();else if(r==='snapshot')h=vSnapshot();else if(r==='journey'||r==='today'||r==='tracker')h=vJourney();else if(r==='routine')h=vRoutine();else if(r==='routine-detail')h=vRoutineDetail();else if(r==='products')h=vProducts();else if(r==='product-detail')h=vProductDetail();else if(r==='scan-product')h=vScanProduct();else if(r==='recommendations')h=vRecs();else if(r==='vendors')h=vVendors();else if(r==='reminders')h=vReminders();else if(r==='progress')h=vProgress();else if(r==='learn')h=vLearn();else if(r==='lesson')h=vLesson();else if(r==='level')h=vLevel();else if(r==='achievements')h=vAch();else if(r==='assistant')h=vAssistant();else if(r==='profile')h=vProfile();else h=vJourney();
 const TITLES={'routine-detail':'Step details','product-detail':'Product analysis','scan-product':'Can I use this?','recommendations':'Recommendations','vendors':'Vendor compare','reminders':'Reminders','learn':'Lessons','lesson':'Lesson','level':'Skin Level','achievements':'Achievements','quiz':'Onboarding','scan-intro':'Skin scan','scan-cam':'Scanning','analysis':'Analysis','snapshot':'Skin profile','routine':'Routine','products':'Products','progress':'Progress','assistant':'Coach','profile':'Profile'};
 // Auto back header on every pushed screen (tab roots excluded)
 if(canGoBack()&&TITLES[r])h=topbar(TITLES[r])+h;
 app.innerHTML=h+(S.pendingLevelUp!=null?levelModal():'')+(S.pendingAch?achModal():'');document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.nav===S.tab));icons();}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{const t=b.dataset.nav;S.tab=t;S.hist=[];if(t==='scan')setRoute('scan-intro',{replace:true});else if(t==='routine')setRoute('routine',{replace:true});else if(t==='assistant')setRoute('assistant',{replace:true});else if(t==='profile')setRoute('profile',{replace:true});else setRoute('journey',{replace:true})});
document.addEventListener('keydown',e=>{if(e.key==='Escape')back()});
window.addEventListener('popstate',()=>{if(canGoBack()){back()}});
const rb=$('#resetDemo');if(rb)rb.onclick=()=>{localStorage.removeItem('dermly_full');location.reload()};
calcStreak();render();icons();
